name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts

      - name: SSH into Server and Build
        run: |
          ssh ${{ secrets.SSH_SERVER }} << 'EOF'
            cd ~/blog-server-go-mongoDB
            git pull origin main
            docker compose down
            docker compose up -d --build
            exit
          EOF
